### ISSUE TITLE
The road towards 1.0.0 and beyond

### ISSUE THREAD

**Issue by SijmenHuizenga** [dbader/schedule#412]
Hi everyone,

Over the last few years, ideas and changes have been accumulating. Now we are picking up development again! As a result there will be new releases :partying_face:. In this post I will outline what the next release will look like and share my ideas about the future. I would love to hear what you think!

---
### 1.0.0

The first priority is to solidify the current feature set. Release 1.0.0 will be a modern version of the current library with mostly bug fixes, without new features. I think the following things should be included:

- [x] Drop python 2 support  #409
- [x] New documentation #395
- [x] Bugfix: Make long-running jobs not skip periods #404
- [x] Bugfix: hour.at('MM:SS') parsing bug #290
- [x] Bugfix: Make idle_seconds return None when no jobs are scheduled #401 
- [x] Bugfix: tuesday.at('HH:MM:SS') where HMS=now+10s doesn't run today #331

This list of bugfixes wouldn't have been possible without your help, thank you a lot!

A few of these changes are technically-speaking 'breaking changes' because the library will behave differently (return a different value, schedule a job at a different time) in some special cases. If someone is (unknowingly) relying on buggy behavior it could break their code. Also, we are dropping python 2 support, which is quite major. To be on the safe side there will be a major release bump.

What other bug / breaking change do you think should be included?

---

### Beyond 1.0.0

With a solid base, we can do anything!! But should we do everything? Let's take a step back :thinking:

This library is built around the idea of simplicity. The api is simple to use and the source code is easy to understand. To me simplicity includes staying away from too niche features and features that are too complex to implement correctly. 

Schedule is here for little scheduling needs, if one needs more advanced scheduling APSchedule will be a better friend :relaxed:

Adding new features while keeping simplicity will be a challenge, one that we can only overcome through collaboration and conversation. Lucky you are all amazing collaborators so I'm sure we will find a way :smiling_face_with_three_hearts:.

What do you think? Is this the direction you would like schedule to see go, or do you rather see something different?
